"""
EvidenceProvider — abstract base class for all provider adapters.

Contract
--------
Every concrete provider must implement:
  async def search(query, max_results, from_date) -> list[EvidenceItem]

And must set:
  self.name        — unique identifier string used in logs and results
  self.source_type — SourceType enum value

Error handling contract
-----------------------
Each provider is responsible for catching its own network / API errors and
raising one of the following so the orchestrator can handle them uniformly:

  ProviderTimeoutError     — request timed out
  ProviderRateLimitError   — HTTP 429 or equivalent
  ProviderAuthError        — invalid / missing API key
  ProviderUnavailableError — 5xx or connection failure
  ProviderNoResultsError   — successful call but zero items returned

The orchestrator (evidence_service.py) catches all ProviderError subclasses,
logs them, and continues with remaining providers.
"""

from __future__ import annotations

import abc
from datetime import datetime
from typing import Optional

from app.evidence.schema import EvidenceItem, SourceType


# ── Provider-specific exceptions ──────────────────────────────────────────────

class ProviderError(Exception):
    """Base class for all provider-level errors."""
    def __init__(self, provider: str, message: str):
        super().__init__(f"[{provider}] {message}")
        self.provider = provider
        self.message  = message


class ProviderTimeoutError(ProviderError):
    pass


class ProviderRateLimitError(ProviderError):
    pass


class ProviderAuthError(ProviderError):
    pass


class ProviderUnavailableError(ProviderError):
    pass


class ProviderNoResultsError(ProviderError):
    pass


# ── Abstract base ─────────────────────────────────────────────────────────────

class EvidenceProvider(abc.ABC):
    """
    Abstract base class for evidence providers.

    Subclasses must implement `search()` and set `name` + `source_type`.
    They must NOT expose API keys to callers — keys are read from env vars
    in __init__ and never returned in any method or property.
    """

    name:        str
    source_type: SourceType

    @abc.abstractmethod
    async def search(
        self,
        query:       str,
        max_results: int              = 10,
        from_date:   Optional[datetime] = None,
    ) -> list[EvidenceItem]:
        """
        Search for articles matching `query`.

        Parameters
        ----------
        query       : Search string (generated by query_extractor).
        max_results : Maximum number of items to return.
        from_date   : If provided, restrict to articles published after this date.

        Returns
        -------
        list[EvidenceItem] — may be empty.

        Raises
        ------
        ProviderTimeoutError, ProviderRateLimitError, ProviderAuthError,
        ProviderUnavailableError, ProviderNoResultsError
        """
        ...

    @property
    def is_configured(self) -> bool:
        """
        Return True if this provider has the credentials / config it needs.
        The orchestrator skips unconfigured providers rather than erroring.
        """
        return True

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} name={self.name!r}>"
